# Basic
title: canaddy
subtitle: 个人站
description: 
creator: <a href="http://canaddy.github.io">@canaddy</a>

url: "http://canaddy.github.io"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客主页

# Navigation buttons in the front page.s
nav:
    - {title: 所有文章, description: archive, url: '/archive'}   
    - {title: 标签, description: tags, url: '/tags'}      
    

# 友情链接
flink:
    # - {title: TakingDataSDK博客, description: TakingDataSDK博客, url: 'http://talkingdata.me'}     
    

# Pagination
# 
gems: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: canaddy
    duoshuo: canaddy 

# Social
social:
    weibo: canaddy
    github: canaddy
    # twitter: 
    mail: 419354025@qq.com

# 百度统计 
# 使用博客模板请去掉或者更换 id 
baidu:
    id: 2a6da53852a1917fdad2e77009723c52 

# Google Analytics
# 使用博客模板请去掉或者更换 id
# ga:
#     id: UA-84134159-3   
#     host: auto  
